### PR TITLE
Add: Support to send events in batch

### PR DESCRIPTION
**Pull request by keyur9**
Add: Support to send events in batch
Fix: Sampling events when using Celery
Refactor: Remove logger and use print message
Refactor: README.md
Bump version to 1.3.9

### CODE REVIEW

**Comment by dkm199** [comment]
discussed with Keyur about to optimize the code so its easy to read/maintain, will merge after that

**Review by dgilling — COMMENTED** [review]
Can we add a "last_event_job_run/last_config_job_run" kind of like how OpenResty has queue_scheduled_time? Worried if thread dies for whatever reason and no more events sent. Let's also set a max size of Queue such as 10k (assuming 5kb events this would be 50 MB).  Ensure block is false and handle exception.

**Review by dkm199 — APPROVED** [review]
you tested middleware_pre19.py also?

**Comment by keyur9** [comment]
Yes, tested with Django1.9 (middleware_pre19) also.

**Pull request merged**
